### PR TITLE
Updates for PureScript 0.9.3

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
Oops, just noticed there's another PR, close?

**Comment by hdgarrood** [comment]
Thanks for this. Re: closing this, it depends. The other one got held up because I preferred not to merge until `Partial` constraints were all in the right places; for example, `headDigit` and `tailDigit` should certainly have `Partial` constraints. There's not been any progress on that other PR for a while. I'd happily merge this one if you felt like tackling the `Partial` constraints issue.

By the way, I'm curious to know if you're benefitting from this library - are you doing something where using one of the types in this library is giving you faster code than using `List` or `Array` or anything else?

**Comment by jacereda** [comment]
I'm not using it, I just wanted to do some benchmarking for https://github.com/jacereda/purescript-slices and right after getting this to compile I got a bunch of work to do. I'll probably come back after finishing the paid stuff.

**Comment by hdgarrood** [comment]
Ah, ok, cool. :)

**Comment by hdgarrood** [comment]
Fixed in #26.

**Pull request closed without merging**
